# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/86d2a0e3-29e0-4322-b145-9fe8de7937f2";
      fsType = "ext4";
      options = [
        "nofail" # Prevent system from failing if this drive doesn't mount
      ];
    };

  fileSystems."/hdd1" =
    { device = "/dev/disk/by-uuid/8d9d8130-956b-47f2-8200-988d6db43389";
      fsType = "ext4";
      options = [
        "nofail" # Prevent system from failing if this drive doesn't mount
      ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fb511b05-d6e9-4bd9-b3bb-80d38ffa7fa3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
